name: Metrics
on:
  # Se ejecuta a medianoche
  schedule: [{cron: "0 0 * * *"}]
  # Se ejecuta si haces push a main/master
  push: {branches: ["master", "main"]}
  # Permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configuración básica
          user: mauri101-Ar
          template: classic
          base: "" 
          config_timezone: America/Argentina/Buenos_Aires
          
          # === AQUÍ ESTÁ LA SOLUCIÓN ===
          
          # 1. Le decimos que mire también donde colaboras, no solo los tuyos
          repositories_affiliations: owner, collaborator
          
          # Configuración de Lenguajes
          plugin_languages: yes
          
          # 2. Agregamos 'jupyter notebook' para que no cuente el JSON pesado como código Python
          plugin_languages_ignored: >-
            html, css, tex, kvlang, makefile, jupyter notebook
            
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          
          # Opcional: Si quieres ser muy preciso y analizar commits en lugar de archivos
          # (consume más recursos pero es más exacto para Bash/R vs Python)
          # plugin_languages_indepth: yes
          
          # Archivo de salida
          filename: github-metrics.svg
